import "../../components/styles/variables.linaria.global";
import "../../components/styles/styles.linaria.global";

import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import { notFound } from "next/navigation";

import { locales } from "../../../i18n.config";

const sourceSansPro = Source_Sans_3({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--theme-fonts-familyHeadings",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: (typeof locales)[number] };
}) {
  if (!locales.includes(locale)) {
    notFound();
  }

  return (
    <html lang={locale} className={sourceSansPro.variable}>
      <body>{children}</body>
    </html>
  );
}
